name: plasmabio-template-r adapted for demo-r
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook>=7.4,<8
  - jupyter-resource-usage>=1,<2
  - jupyterlab-topbar-text >=1.1.0,<2
  - nodejs>=20
 
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - jupyterlab-variableinspector
  
  # R environment (version for Ubuntu 24.04)
  - r-irkernel>1.3
  - r-base>=4.3
  - r-tidyverse
  - r-essentials
  - r-repr

  # Build tools required for Ubuntu 24.04
  - gxx_linux-64
  - gcc_linux-64
  - gfortran_linux-64
  
  # JupyterLab Variable inspector
  - pip
  - pip:
    - watermark
  
