name: plasmabio-template-r
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority for Ubuntu 24.04
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Jupyter dependencies - updated for Ubuntu 24.04
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook>=7.4,<8
  - jupyter-resource-usage>=1,<2
  - jupyterlab-topbar-text>=1.1.0,<2
  - nodejs>=20
  
  # Python and pip
  - pip
  
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive

 # JupyterLab Variable inspector - inactivated
  # https://github.com/lckr/jupyterlab-variableInspector
  # - jupyterlab-variableinspector
  # Disabled due to bug https://github.com/lckr/jupyterlab-variableInspector/issues/122
  # - r-repr
  # - pip:
    # - lckr-jupyterlab-variableinspector
  
  # R environment - updated for Ubuntu 24.04
  - r-irkernel>=1.3
  - r-base>=4.3
  - r-tidyverse
  - r-essentials
  - r-repr

   # Build tools required for Ubuntu 24.04
  - gxx_linux-64
  - gcc_linux-64
  - gfortran_linux-64

 
